mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username:
    password:
    url: jdbc:ucanaccess://c:/Users/huang/Desktop/ZJU-ICL Database.accdb
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
